#pragma once
#include <glm/glm.hpp>
#include <complex>

struct Wavefunction {
    int n, l, m;
    Wavefunction(int n_, int l_, int m_) : n(n_), l(l_), m(m_) {}

    double factorial(int k) const {
        if (k <= 1) return 1.0;
        double result = 1.0;
        for (int i = 2; i <= k; ++i) result *= i;
        return result;
    }

    double laguerre(int k, int alpha, double x) const {
        if (k == 0) return 1.0;
        if (k == 1) return 1.0 + (double)alpha - x;

        double L_k_minus_2 = 1.0;
        double L_k_minus_1 = 1.0 + (double)alpha - x;
        double L_k = 0.0;

        for (int i = 2; i <= k; ++i) {
            // Standard three-term recurrence: 
            // L_i = ((2*i - 1 + alpha - x) * L_i-1 - (i - 1 + alpha) * L_i-2) / i
            L_k = ((2.0 * i - 1.0 + (double)alpha - x) * L_k_minus_1 - 
                ((double)i - 1.0 + (double)alpha) * L_k_minus_2) / (double)i;
                
            L_k_minus_2 = L_k_minus_1;
            L_k_minus_1 = L_k;
        }
        return L_k;
    }

    float radial(float r, int n, int l) const {
        double a0 = 1.0;
        double dr = (double)r;
        double rho = (2.0 * dr) / (n * a0);
        
        // Normalization constant using double to handle large factorials
        double term1 = std::pow(2.0 / (n * a0), 3.0);
        double fact_top = factorial(n - l - 1);
        double fact_bottom = factorial(n + l); // (n+l)!
        
        // Using (n+l)!^3 as per common wavefunction normalization
        double norm = std::sqrt(term1 * fact_top / (2.0 * n * fact_bottom));

        double result = norm 
                    * std::exp(-rho / 2.0) 
                    * std::pow(rho, (double)l) 
                    * laguerre(n - l - 1, 2 * l + 1, rho);


        return (float)result;
    }

    float angular(int l, int m, float theta, float phi) const {
        // Hardcoded spherical harmonic (generated by claude)
        if (l == 0)                    return 0.282095f;
        if (l == 1 && m ==  0)         return 0.488603f * glm::cos(theta);
        if (l == 1 && m ==  1)         return 0.488603f * glm::sin(theta) * glm::cos(phi);
        if (l == 1 && m == -1)         return 0.488603f * glm::sin(theta) * glm::sin(phi);
        if (l == 2 && m ==  0)         return 0.315392f * (3*glm::pow(glm::cos(theta),2.0f) - 1);
        if (l == 2 && m ==  1)         return 1.092548f * glm::sin(theta) * glm::cos(theta) * glm::cos(phi);
        if (l == 2 && m == -1)         return 1.092548f * glm::sin(theta) * glm::cos(theta) * glm::sin(phi);
        if (l == 2 && m ==  2)         return 0.546274f * glm::pow(glm::sin(theta),2.0f) * glm::cos(2*phi);
        if (l == 2 && m == -2)         return 0.546274f * glm::pow(glm::sin(theta),2.0f) * glm::sin(2*phi);
        return 0.0f;
    }

    float energy() const {
        return -0.5f / (float)(n * n);
    }

    // Evaluate the wavefunction at a given point
    std::complex<float> evaluate(const glm::vec3& point, float t) const {
    //float evaluate(const glm::vec3& point, float t) const {
        float r = glm::length(point);
        if (r < 1e-6f) return 0.0f;  // guard against origin
        float theta = glm::acos(point.z / r);
        float phi = glm::atan(point.y, point.x);

        float psi = radial(r, n, l) * angular(l, m, theta, phi);
        float phase = -energy() * t;
        return psi * std::complex<float>(glm::cos(phase), glm::sin(phase));
    }
};